spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/likarnyam
    username: postgres
    password: ${DB_PASSWORD:changeme}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080